### ISSUE TITLE
improve makefile docs / refactor makefile

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/liqwid-contracts#10]
lets either document make scripts that require a nix shell in the readme, or make them invoke the nix-shell directly

lets unify the 3-stage `pab` scripts into a simple single command

lets make sure at least the make scripts that are intended to be run are documented in the readme (ie. the scripts that aren't invoked as a make dependency)

**Comment by t1lde** [comment]
I've done this in 9441a75081280acbb8a7d6b4468340e5b53b8694, it could be refactored further in the future but it's moot at the moment until PAB actually works.

**Comment by Benjmhart** [comment]
looks great, I'll close the issue and move the card to done.
