### ISSUE TITLE
Generate bytecode

### ISSUE THREAD

**Issue by markflorisson** [mlabs-haskell/liqwid-contracts#4]
since this is (Hypothetically handled by `pab` + template haskell I'm reinterpreting this to be 'get plutus code such that it compiles', which we have achieved.

- BH

**Comment by Benjmhart** [comment]
so creating bytecode isn't really how Plutus is generated,    the plutus-core code is serialized before it becomes bytecode and seems to be deployed on chain by way of `plutus-pab`.
