### ISSUE TITLE
nix-shell SHA mismatch on plutus

### ISSUE THREAD

**Issue by Benjmhart** [mlabs-haskell/liqwid-contracts#6]
after running `nix-collect-garbage` the `nix-shell` will often fail to instantiate due to a hash mismatch.

current working theory: A deep clone causes the hash to change due to branch info?

**Comment by t1lde** [comment]
I've added some documentation in the README on how to work around this for now. Additionally, I added a `make fix_rev` target that recalculates the hash for the current rev set in the json file.
